name: Deploy to Thamara Cloud

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # خطوة: نسخ الملفات المطلوبة فقط إلى مجلد deploy
      - name: Prepare Deployment Folder
        run: |
          mkdir deploy
          rsync -av --progress ./zidan/ ./deploy/ \
            --exclude='.git*' \
            --exclude='.github/' \
            --exclude='node_modules/' \
            --exclude='.env*' \
            --exclude='.vscode/' \
            --exclude='.idea/' \
            --exclude='*.log' \
            --exclude='.DS_Store'

      # خطوة: رفع المجلد deploy فقط
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 213.239.220.209
          username: osama74
          password: LVcWhvv8m8*se!h3
          protocol: ftp
          port: 21
          security: loose
          timeout: 120000
          server-dir: /httpdocs/z/
          dangerous-clean-slate: false